name: numeric_keyboard
description: Flutter plugin to display a simple numeric keyboard on Android & iOS.
version: 1.2.0
homepage: https://github.com/OmarYehiaDev/numeric_keyboard

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter